version: '3.7'
services:
  locust:
    image: locustio/locust:2.36.2
    working_dir: /mnt/locust
    volumes:
      - ./:/mnt/locust
    command: >
      locust -f locustfile.py \
            --master \
            --master-bind-host=0.0.0.0 \
            --master-bind-port=4001 \
            --web-host=0.0.0.0 \
            --web-port=8089
    ports:
      - "4001:4001"
      - "8089:8089"

  prometheus:
    image: prom/prometheus:v2.50.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
    # Empty mapping indicates a named volume with default settings
    {}
